//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Donnee.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Donnee.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter un objet null.
        /// </summary>
        internal static string AjouterObjeNull {
            get {
                return ResourceManager.GetString("AjouterObjeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur De Validation.
        /// </summary>
        internal static string ErreurDeValidation {
            get {
                return ResourceManager.GetString("ErreurDeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Ordre By Null Invalide.
        /// </summary>
        internal static string ExpressionOrdreByNullInvalide {
            get {
                return ResourceManager.GetString("ExpressionOrdreByNullInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre Null Invalide.
        /// </summary>
        internal static string FiltreNullInvalide {
            get {
                return ResourceManager.GetString("FiltreNullInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusion Null Invalide.
        /// </summary>
        internal static string InclusionNullInvalide {
            get {
                return ResourceManager.GetString("InclusionNullInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index de Page Invalide.
        /// </summary>
        internal static string IndexDePageInvalide {
            get {
                return ResourceManager.GetString("IndexDePageInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre De Pages Invalide.
        /// </summary>
        internal static string NombreDePagesInvalide {
            get {
                return ResourceManager.GetString("NombreDePagesInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer un objet null.
        /// </summary>
        internal static string SupprimerObjetNull {
            get {
                return ResourceManager.GetString("SupprimerObjetNull", resourceCulture);
            }
        }
    }
}
