//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteClient.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de livraison.
        /// </summary>
        public static string AdresseLivraison {
            get {
                return ResourceManager.GetString("AdresseLivraison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant.
        /// </summary>
        public static string CategorieID {
            get {
                return ResourceManager.GetString("CategorieID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant client .
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        public static string CodePostal {
            get {
                return ResourceManager.GetString("CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        public static string Commande {
            get {
                return ResourceManager.GetString("Commande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compagnie.
        /// </summary>
        public static string Compagnie {
            get {
                return ResourceManager.GetString("Compagnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compangnie.
        /// </summary>
        public static string Compangnie {
            get {
                return ResourceManager.GetString("Compangnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creer.
        /// </summary>
        public static string Creer {
            get {
                return ResourceManager.GetString("Creer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la commande.
        /// </summary>
        public static string DateCommande {
            get {
                return ResourceManager.GetString("DateCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la livraison.
        /// </summary>
        public static string DateLivraison {
            get {
                return ResourceManager.GetString("DateLivraison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string Fornisseur {
            get {
                return ResourceManager.GetString("Fornisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string Fournisseur {
            get {
                return ResourceManager.GetString("Fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant.
        /// </summary>
        public static string Identifiant {
            get {
                return ResourceManager.GetString("Identifiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des  produits.
        /// </summary>
        public static string Lesproduitenstock {
            get {
                return ResourceManager.GetString("Lesproduitenstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des clients.
        /// </summary>
        public static string ListClients {
            get {
                return ResourceManager.GetString("ListClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des Commandes.
        /// </summary>
        public static string ListCommandes {
            get {
                return ResourceManager.GetString("ListCommandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des fournisseurs.
        /// </summary>
        public static string ListFournisseurs {
            get {
                return ResourceManager.GetString("ListFournisseurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livreur.
        /// </summary>
        public static string Livreur {
            get {
                return ResourceManager.GetString("Livreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string NomCategorie {
            get {
                return ResourceManager.GetString("NomCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string NomFornisseur {
            get {
                return ResourceManager.GetString("NomFornisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libelé.
        /// </summary>
        public static string NomProduit {
            get {
                return ResourceManager.GetString("NomProduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        public static string Nouveau {
            get {
                return ResourceManager.GetString("Nouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un nouveau produit.
        /// </summary>
        public static string Nouveauproduit {
            get {
                return ResourceManager.GetString("Nouveauproduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string Pays {
            get {
                return ResourceManager.GetString("Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix unitaire.
        /// </summary>
        public static string PrixUnitaire {
            get {
                return ResourceManager.GetString("PrixUnitaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        public static string Produit {
            get {
                return ResourceManager.GetString("Produit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant.
        /// </summary>
        public static string ProduitID {
            get {
                return ResourceManager.GetString("ProduitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produits.
        /// </summary>
        public static string Produits {
            get {
                return ResourceManager.GetString("Produits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantite.
        /// </summary>
        public static string Quantite {
            get {
                return ResourceManager.GetString("Quantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la liste.
        /// </summary>
        public static string RetourListe {
            get {
                return ResourceManager.GetString("RetourListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionner.
        /// </summary>
        public static string Selectionner {
            get {
                return ResourceManager.GetString("Selectionner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total des commandes.
        /// </summary>
        public static string TotalCommandes {
            get {
                return ResourceManager.GetString("TotalCommandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total produits.
        /// </summary>
        public static string TotalProduits {
            get {
                return ResourceManager.GetString("TotalProduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans le stock.
        /// </summary>
        public static string UnitesDansStock {
            get {
                return ResourceManager.GetString("UnitesDansStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string Ville {
            get {
                return ResourceManager.GetString("Ville", resourceCulture);
            }
        }
    }
}
